server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"


logger:
  level : "all"
  stdout: true


# GF-CLI工具配置
gfcli:
    # 自定义DAO生成配置(默认是读取database配置)
    gfcli.gen.dao:
        link   : "mysql:root:mysql@tcp(192.168.212.117:3306)/myapp"
        descriptionTag :   true
        noModelComment :   true