[database]
    [[database.default]]
        host         = "127.0.0.1"
        port         = "3306"
        user         = "root"
        pass         = "password"
        name         = "example_app"
        type         = "mysql"
        role         = "master"
        debug        = "true"
        dryrun       = 1
        weight       = "100"
        charset      = "utf8"
        linkinfo     = ""
        maxIdle      = "10"
        maxOpen      = "100"
        maxLifetime  = "30"