// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PlanMetas is the golang structure of table plan_metas for DAO operations like Where/Data.
type PlanMetas struct {
	g.Meta     `orm:"table:plan_metas, do:true"`
	Id         interface{} //
	PlanId     interface{} //
	CategoryId interface{} //
}
