// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_0620/internal/service/internal/dao/internal"
)

// oauthAccessTokensDao is the data access object for table oauth_access_tokens.
// You can define custom methods on it to extend its functionality as you wish.
type oauthAccessTokensDao struct {
	*internal.OauthAccessTokensDao
}

var (
	// OauthAccessTokens is globally public accessible object for table oauth_access_tokens operations.
	OauthAccessTokens = oauthAccessTokensDao{
		internal.NewOauthAccessTokensDao(),
	}
)

// Fill with you ideas below.