// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_0620/internal/service/internal/dao/internal"
)

// oauthAuthCodesDao is the data access object for table oauth_auth_codes.
// You can define custom methods on it to extend its functionality as you wish.
type oauthAuthCodesDao struct {
	*internal.OauthAuthCodesDao
}

var (
	// OauthAuthCodes is globally public accessible object for table oauth_auth_codes operations.
	OauthAuthCodes = oauthAuthCodesDao{
		internal.NewOauthAuthCodesDao(),
	}
)

// Fill with you ideas below.