// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_0620/internal/service/internal/dao/internal"
)

// oauthPersonalAccessClientsDao is the data access object for table oauth_personal_access_clients.
// You can define custom methods on it to extend its functionality as you wish.
type oauthPersonalAccessClientsDao struct {
	*internal.OauthPersonalAccessClientsDao
}

var (
	// OauthPersonalAccessClients is globally public accessible object for table oauth_personal_access_clients operations.
	OauthPersonalAccessClients = oauthPersonalAccessClientsDao{
		internal.NewOauthPersonalAccessClientsDao(),
	}
)

// Fill with you ideas below.