// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_0620/internal/service/internal/dao/internal"
)

// passwordResetsDao is the data access object for table password_resets.
// You can define custom methods on it to extend its functionality as you wish.
type passwordResetsDao struct {
	*internal.PasswordResetsDao
}

var (
	// PasswordResets is globally public accessible object for table password_resets operations.
	PasswordResets = passwordResetsDao{
		internal.NewPasswordResetsDao(),
	}
)

// Fill with you ideas below.