// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_0620/internal/service/internal/dao/internal"
)

// personalAccessTokensDao is the data access object for table personal_access_tokens.
// You can define custom methods on it to extend its functionality as you wish.
type personalAccessTokensDao struct {
	*internal.PersonalAccessTokensDao
}

var (
	// PersonalAccessTokens is globally public accessible object for table personal_access_tokens operations.
	PersonalAccessTokens = personalAccessTokensDao{
		internal.NewPersonalAccessTokensDao(),
	}
)

// Fill with you ideas below.