// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_0620/internal/dao/internal"
)

// internalPlansDao is internal type for wrapping internal DAO implements.
type internalPlansDao = *internal.PlansDao

// plansDao is the data access object for table plans.
// You can define custom methods on it to extend its functionality as you wish.
type plansDao struct {
	internalPlansDao
}

var (
	// Plans is globally public accessible object for table plans operations.
	Plans = plansDao{
		internal.NewPlansDao(),
	}
)

// Fill with you ideas below.
