// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_0620/internal/dao/internal"
)

// internalPlanMetasDao is internal type for wrapping internal DAO implements.
type internalPlanMetasDao = *internal.PlanMetasDao

// planMetasDao is the data access object for table plan_metas.
// You can define custom methods on it to extend its functionality as you wish.
type planMetasDao struct {
	internalPlanMetasDao
}

var (
	// PlanMetas is globally public accessible object for table plan_metas operations.
	PlanMetas = planMetasDao{
		internal.NewPlanMetasDao(),
	}
)

// Fill with you ideas below.
