// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
)

// Migrations is the golang structure of table migrations for DAO operations like Where/Data.
type Migrations struct {
g.Meta `orm:"table:migrations, do:true"`
    Id interface{} //   
    Migration interface{} //   
    Batch interface{} //   
}