// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// OauthAccessTokens is the golang structure of table oauth_access_tokens for DAO operations like Where/Data.
type OauthAccessTokens struct {
g.Meta `orm:"table:oauth_access_tokens, do:true"`
    Id interface{} //   
    UserId interface{} //   
    ClientId interface{} //   
    Name interface{} //   
    Scopes interface{} //   
    Revoked interface{} //   
    CreatedAt *gtime.Time //   
    UpdatedAt *gtime.Time //   
    ExpiresAt *gtime.Time //   
}