// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// OauthAuthCodes is the golang structure of table oauth_auth_codes for DAO operations like Where/Data.
type OauthAuthCodes struct {
g.Meta `orm:"table:oauth_auth_codes, do:true"`
    Id interface{} //   
    UserId interface{} //   
    ClientId interface{} //   
    Scopes interface{} //   
    Revoked interface{} //   
    ExpiresAt *gtime.Time //   
}