// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// OauthClients is the golang structure of table oauth_clients for DAO operations like Where/Data.
type OauthClients struct {
g.Meta `orm:"table:oauth_clients, do:true"`
    Id interface{} //   
    UserId interface{} //   
    Name interface{} //   
    Secret interface{} //   
    Provider interface{} //   
    Redirect interface{} //   
    PersonalAccessClient interface{} //   
    PasswordClient interface{} //   
    Revoked interface{} //   
    CreatedAt            *gtime.Time //   
    UpdatedAt            *gtime.Time //   
}