// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// OauthPersonalAccessClients is the golang structure of table oauth_personal_access_clients for DAO operations like Where/Data.
type OauthPersonalAccessClients struct {
g.Meta `orm:"table:oauth_personal_access_clients, do:true"`
    Id interface{} //   
    ClientId interface{} //   
    CreatedAt *gtime.Time //   
    UpdatedAt *gtime.Time //   
}