// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// OauthRefreshTokens is the golang structure of table oauth_refresh_tokens for DAO operations like Where/Data.
type OauthRefreshTokens struct {
g.Meta `orm:"table:oauth_refresh_tokens, do:true"`
    Id interface{} //   
    AccessTokenId interface{} //   
    Revoked interface{} //   
    ExpiresAt     *gtime.Time //   
}