// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure of table users for DAO operations like Where/Data.
type Users struct {
g.Meta `orm:"table:users, do:true"`
    Id interface{} //   
    Name interface{} //   
    Email interface{} //   
    EmailVerifiedAt *gtime.Time //   
    Password interface{} //   
    RememberToken interface{} //   
    CreatedAt       *gtime.Time //   
    UpdatedAt       *gtime.Time //   
}