// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// FailedJobs is the golang structure for table failed_jobs.
type FailedJobs struct {
    Id         uint64      `json:"id"         description:""`  
    Uuid       string      `json:"uuid"       description:""`  
    Connection string      `json:"connection" description:""`  
    Queue      string      `json:"queue"      description:""`  
    Payload    string      `json:"payload"    description:""`  
    Exception  string      `json:"exception"  description:""`  
    FailedAt   *gtime.Time `json:"failedAt"   description:""`  
}