// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FailedJobs is the golang structure for table failed_jobs.
type FailedJobs struct {
	Id         uint64      `json:"id"         ` //
	Uuid       string      `json:"uuid"       ` //
	Connection string      `json:"connection" ` //
	Queue      string      `json:"queue"      ` //
	Payload    string      `json:"payload"    ` //
	Exception  string      `json:"exception"  ` //
	FailedAt   *gtime.Time `json:"failedAt"   ` //
}
