// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Migrations is the golang structure for table migrations.
type Migrations struct {
	Id        uint   `json:"id"        ` //
	Migration string `json:"migration" ` //
	Batch     int    `json:"batch"     ` //
}
