// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity



// Migrations is the golang structure for table migrations.
type Migrations struct {
    Id        uint   `json:"id"        description:""`  
    Migration string `json:"migration" description:""`  
    Batch     int    `json:"batch"     description:""`  
}