// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// OauthAccessTokens is the golang structure for table oauth_access_tokens.
type OauthAccessTokens struct {
    Id        string      `json:"id"        description:""`  
    UserId    uint64      `json:"userId"    description:""`  
    ClientId  uint64      `json:"clientId"  description:""`  
    Name      string      `json:"name"      description:""`  
    Scopes    string      `json:"scopes"    description:""`  
    Revoked   int         `json:"revoked"   description:""`  
    CreatedAt *gtime.Time `json:"createdAt" description:""`  
    UpdatedAt *gtime.Time `json:"updatedAt" description:""`  
    ExpiresAt *gtime.Time `json:"expiresAt" description:""`  
}