// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// OauthRefreshTokens is the golang structure for table oauth_refresh_tokens.
type OauthRefreshTokens struct {
    Id            string      `json:"id"            description:""`  
    AccessTokenId string      `json:"accessTokenId" description:""`  
    Revoked       int         `json:"revoked"       description:""`  
    ExpiresAt     *gtime.Time `json:"expiresAt"     description:""`  
}