// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// OauthClients is the golang structure for table oauth_clients.
type OauthClients struct {
    Id                   uint64      `json:"id"                   description:""`  
    UserId               uint64      `json:"userId"               description:""`  
    Name                 string      `json:"name"                 description:""`  
    Secret               string      `json:"secret"               description:""`  
    Provider             string      `json:"provider"             description:""`  
    Redirect             string      `json:"redirect"             description:""`  
    PersonalAccessClient int         `json:"personalAccessClient" description:""`  
    PasswordClient       int         `json:"passwordClient"       description:""`  
    Revoked              int         `json:"revoked"              description:""`  
    CreatedAt            *gtime.Time `json:"createdAt"            description:""`  
    UpdatedAt            *gtime.Time `json:"updatedAt"            description:""`  
}