// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// OauthAuthCodes is the golang structure for table oauth_auth_codes.
type OauthAuthCodes struct {
    Id        string      `json:"id"        description:""`  
    UserId    uint64      `json:"userId"    description:""`  
    ClientId  uint64      `json:"clientId"  description:""`  
    Scopes    string      `json:"scopes"    description:""`  
    Revoked   int         `json:"revoked"   description:""`  
    ExpiresAt *gtime.Time `json:"expiresAt" description:""`  
}