// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// OauthPersonalAccessClients is the golang structure for table oauth_personal_access_clients.
type OauthPersonalAccessClients struct {
    Id        uint64      `json:"id"        description:""`  
    ClientId  uint64      `json:"clientId"  description:""`  
    CreatedAt *gtime.Time `json:"createdAt" description:""`  
    UpdatedAt *gtime.Time `json:"updatedAt" description:""`  
}