// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PersonalAccessTokens is the golang structure for table personal_access_tokens.
type PersonalAccessTokens struct {
	Id            uint64      `json:"id"            ` //
	TokenableType string      `json:"tokenableType" ` //
	TokenableId   uint64      `json:"tokenableId"   ` //
	Name          string      `json:"name"          ` //
	Token         string      `json:"token"         ` //
	Abilities     string      `json:"abilities"     ` //
	LastUsedAt    *gtime.Time `json:"lastUsedAt"    ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
