// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// PersonalAccessTokens is the golang structure for table personal_access_tokens.
type PersonalAccessTokens struct {
    Id            uint64      `json:"id"            description:""`  
    TokenableType string      `json:"tokenableType" description:""`  
    TokenableId   uint64      `json:"tokenableId"   description:""`  
    Name          string      `json:"name"          description:""`  
    Token         string      `json:"token"         description:""`  
    Abilities     string      `json:"abilities"     description:""`  
    LastUsedAt    *gtime.Time `json:"lastUsedAt"    description:""`  
    CreatedAt     *gtime.Time `json:"createdAt"     description:""`  
    UpdatedAt     *gtime.Time `json:"updatedAt"     description:""`  
}