// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// PlanMetas is the golang structure for table plan_metas.
type PlanMetas struct {
	Id         uint64 `json:"id"         ` //
	PlanId     int    `json:"planId"     ` //
	CategoryId int    `json:"categoryId" ` //
}
