// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Plans is the golang structure for table plans.
type Plans struct {
	Id        uint64      `json:"id"        ` //
	Name      string      `json:"name"      ` //
	Price     float64     `json:"price"     ` //
	Unit      string      `json:"unit"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	DeletedAt *gtime.Time `json:"deletedAt" ` //
}
