// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// Users is the golang structure for table users.
type Users struct {
    Id              uint64      `json:"id"              description:""`  
    Name            string      `json:"name"            description:""`  
    Email           string      `json:"email"           description:""`  
    EmailVerifiedAt *gtime.Time `json:"emailVerifiedAt" description:""`  
    Password        string      `json:"password"        description:""`  
    RememberToken   string      `json:"rememberToken"   description:""`  
    CreatedAt       *gtime.Time `json:"createdAt"       description:""`  
    UpdatedAt       *gtime.Time `json:"updatedAt"       description:""`  
}