// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// OauthRefreshTokensDao is the data access object for table oauth_refresh_tokens.
type OauthRefreshTokensDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns OauthRefreshTokensColumns // columns contains all the column names of Table for convenient usage.
}

// OauthRefreshTokensColumns defines and stores column names for table oauth_refresh_tokens.
type OauthRefreshTokensColumns struct {
	Id             string //   
    AccessTokenId  string //   
    Revoked        string //   
    ExpiresAt      string //
}

//  oauthRefreshTokensColumns holds the columns for table oauth_refresh_tokens.
var oauthRefreshTokensColumns = OauthRefreshTokensColumns{
	Id:            "id",               
            AccessTokenId: "access_token_id",  
            Revoked:       "revoked",          
            ExpiresAt:     "expires_at",
}

// NewOauthRefreshTokensDao creates and returns a new DAO object for table data access.
func NewOauthRefreshTokensDao() *OauthRefreshTokensDao {
	return &OauthRefreshTokensDao{
		group:   "default",
		table:   "oauth_refresh_tokens",
		columns: oauthRefreshTokensColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OauthRefreshTokensDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *OauthRefreshTokensDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *OauthRefreshTokensDao) Columns() OauthRefreshTokensColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *OauthRefreshTokensDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OauthRefreshTokensDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OauthRefreshTokensDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}