// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-21 11:39:19
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// OauthClientsDao is the data access object for table oauth_clients.
type OauthClientsDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns OauthClientsColumns // columns contains all the column names of Table for convenient usage.
}

// OauthClientsColumns defines and stores column names for table oauth_clients.
type OauthClientsColumns struct {
	Id                    string //   
    UserId                string //   
    Name                  string //   
    Secret                string //   
    Provider              string //   
    Redirect              string //   
    PersonalAccessClient  string //   
    PasswordClient        string //   
    Revoked               string //   
    CreatedAt             string //   
    UpdatedAt             string //
}

//  oauthClientsColumns holds the columns for table oauth_clients.
var oauthClientsColumns = OauthClientsColumns{
	Id:                   "id",                      
            UserId:               "user_id",                 
            Name:                 "name",                    
            Secret:               "secret",                  
            Provider:             "provider",                
            Redirect:             "redirect",                
            PersonalAccessClient: "personal_access_client",  
            PasswordClient:       "password_client",         
            Revoked:              "revoked",                 
            CreatedAt:            "created_at",              
            UpdatedAt:            "updated_at",
}

// NewOauthClientsDao creates and returns a new DAO object for table data access.
func NewOauthClientsDao() *OauthClientsDao {
	return &OauthClientsDao{
		group:   "default",
		table:   "oauth_clients",
		columns: oauthClientsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OauthClientsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *OauthClientsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *OauthClientsDao) Columns() OauthClientsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *OauthClientsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OauthClientsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OauthClientsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}